### PR TITLE
Documenting docker stuff, cleaning up

### PR DESCRIPTION
**Pull request by masone**
- Cleaned up the docs on docker
- Moved some bits from the stripped down READMEs to the docs
- Started removing duplicate documentation from the archive
- Ended up removing the whole archive, there was not much value in the remaining 3 files

### CODE REVIEW

**Comment by masone** [comment]
@mthpvg there is no more archive and no more duplicated docs anymore - any objections?

**Comment by masone** [comment]
Oh and: What's the reason for keeping an archive if all information is properly filed in the new structure 🤔

**Comment by peyerluk** [comment]
> Ended up removing the whole archive, there was not much value in the remaining 3 files

`ARCHIVE/upfrontIO_livingdocs/ideas/document-model.md` is still a good read :) It is a candidate to be implemented in the coming months (at least partially). 

Same goes for the design migrations file.

I moved the content of both of those into Google Drive under `Development`.

**Comment by mthpvg** [comment]
Thanks for that :+1:

**Pull request merged**
