### PR TITLE
WIP: Document Rancher deployment

### PR DESCRIPTION
**Pull request by masone**
💣 WIP

Documentation of the rancher deployment process tackled in epic https://github.com/upfrontIO/livingdocs-server/issues/1113 - this will stay a WIP until all decisions are final

### CODE REVIEW

**Comment by masone** [comment]
Will run into merge conflicts. Copied some of it to the docs manually

**Comment by peyerluk** [comment]
@masone Can we salvage this pr?

**Comment by masone** [comment]
Not at all on my priority list at the moment. I'd like to keep it around though

**Comment by marcbachmann** [comment]
Thanks for assigning me 👍 
I'll work on that.

**Comment by gabrielhase** [comment]
is this still valid?

**Pull request closed without merging**
