### PR TITLE
Add information about dependencies in a livingdoc

### PR DESCRIPTION
**Pull request by mheiniger**
This is the information @gabrielhase dug out from a PR. So it would be good to have it in the documentation too.

### CODE REVIEW

**Comment by gabrielhase** [comment]
@mheiniger We kinda forgot this documentation a bit... sorry about this. Can you change the name `doc` in the editor to `framework`? (the new name we use for the framework everywhere)
Then it is good to merge.

**Comment by mheiniger** [comment]
You mean this: `doc.JsLoader and doc.CssLoader` ?
In the currently deployed editor there is no global framework variable exposed, only doc. I tried it on http://nzz-develop.livingdocs.io and http://www.livingdocs-beta.io

**Comment by gabrielhase** [comment]
Hmmm... I thought they renamed that. @marcbachmann what is the status there?

**Comment by peyerluk** [comment]
@mheiniger Finally landed in 576b3604435b74ec0ee65a351139c1f9e5ac1714

**Pull request closed without merging**
