### PR TITLE
docs(events): in the public API

### PR DESCRIPTION
**Pull request by mthpvg**
@peyerluk first draft for the events API documentation.

### CODE REVIEW

**Comment by peyerluk** [comment]
@mthpvg is it ready for review?

**Comment by mthpvg** [comment]
That's the draft I came up with the time I had left on the last sprint at least :).

**Comment by peyerluk** [comment]
Ok. Thanks. I'll have a look.

**Comment by gabrielhase** [comment]
@peyerluk can you review this?

**Pull request merged**
